name: Terraform Destroy Selected

on:
  workflow_dispatch:  # Triggered manually from GitHub Actions UI

jobs:
  destroy-all:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out the repository to access Terraform files

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1  # Configure AWS credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1  # Specify the AWS region

    - name: Terraform Init and Destroy - Development
      working-directory: ./development  # Set working directory to development environment
      run: |
        terraform init
        terraform destroy -auto-approve

    - name: Terraform Init and Destroy - Staging
      working-directory: ./staging  # Set working directory to staging environment
      run: |
        terraform init
        terraform destroy -auto-approve

    - name: Terraform Init and Destroy - Production
      working-directory: ./production  # Set working directory to production environment
      run: |
        terraform init
        terraform destroy -auto-approve

    - name: Terraform Init and Destroy - Grafana
      working-directory: ./grafana  # Set working directory to Grafana environment
      run: |
        terraform init
        terraform destroy -auto-approve
